#! /bin/csh
#
# Usage: checkAseg sub1 sub2 sub3

setenv SUBJECTS_DIR /Volumes/group/proc/TIGERanalysis/TIGER_FreeSurfer/TIGER_FS_subjDir
set bin = /Volumes/group/proc/TIGERanalysis/TIGER_FreeSurfer/TIGER_FS_bin

foreach sub ($argv)

	echo "----------------------------------------------"
	echo
	echo "Checking segmentation for "$sub
	echo
	freeview -viewport z -zoom 1.45 -v $SUBJECTS_DIR/$sub/mri/brainmask.mgz -v $SUBJECTS_DIR/$sub/mri/aseg.mgz:colormap=lut:lut=$bin/lut.txt:opacity=.15 & 
	echo
	echo "----------------------------------------------"

end
end
