#! /bin/csh
#SBATCH --time=30:00:00
#SBATCH --cpus-per-task=2
#SBATCH --pty=bash


setenv SUBJECTS_DIR /oak/stanford/groups/iang/TIGER_data/TIGER_FreeSurfer/TIGER_FS_subjDir


set fp = /oak/stanford/groups/iang/TIGER_data/TIGER-T1
shift

set sub = $argv

set rawdata = $fp/${sub}-T1/Ax_FSPGR_BRAVO_raw.nii.gz

if (-e $rawdata) then
	echo '****************************************************************** '
	echo '****************************************************************** '
	echo '***************** Working on subject '$sub'********************* '
	echo '****************************************************************** '
	echo '****************************************************************** '

	recon-all -s ${sub}-T1 -i $rawdata -all

	echo '****************************************************************** '
	echo '****************************************************************** '
	echo '****************** finished subject '$sub'********************** '
	echo '****************************************************************** '
	echo '****************************************************************** '
else
	echo
	echo '>> WARNING:'$sub' Ax_FSPGR_BRAVO_raw.nii.gz not found <<'
	echo '>> WARNING:'$sub' Ax_FSPGR_BRAVO_raw.nii.gz not found <<' >> $SUBJECTS_DIR/log.txt
	echo
endif
end
